#!/usr/bin/env sh
bwrap \
	--ro-bind ${BWRAP_ROOT} / \
	--dev-bind /dev /dev \
	--ro-bind /sys /sys \
	--bind-try /tmp /tmp \
	--proc /proc \
	--bind-try /run /run \
	--ro-bind-try /etc/resolv.conf /etc/resolv.conf \
	--ro-bind-try /etc/hosts /etc/hosts \
	--ro-bind-try /etc/nsswitch.conf /etc/nsswitch.conf \
	--ro-bind-try /etc/passwd /etc/passwd \
	--ro-bind-try /etc/group /etc/group \
	--ro-bind-try /etc/localtime /etc/localtime \
	--ro-bind-try ${XDG_RUNTIME_DIR} ${XDG_RUNTIME_DIR} \
	--ro-bind-try /tmp/.X11-unix /tmp/.X11-unix \
	--new-session \
	--chdir / \
	"$@"
